### ISSUE TITLE
Display available ESLint fix in "code actions"

### ISSUE THREAD

**Issue by destegabry** [apexskier/nova-eslint#1]
I'm a React developer and VSCode user, wishing Nova could replace it (I prefer using native applications over Electron ones).

In VSCode, most ESLint errors could be fixed by the editor using the "Quick fix…" contextual menu. This is a very helpful feature in a lot of situations, for example getting a React hook dependency list filled automatically.

<img width="693" alt="Schermata 2020-10-30 alle 09 56 24" src="https://user-images.githubusercontent.com/4654358/97679983-4893e280-1a96-11eb-9f9b-68033622b899.png">

The Nova ESLint plugin let me have the warning/error gracefully displayed in the editor:

<img width="922" alt="Schermata 2020-10-29 alle 09 47 27" src="https://user-images.githubusercontent.com/4654358/97546022-233aa200-19cc-11eb-8c4e-012a522e3796.png">

But the proposed "Quick actions" are not very useful:

<img width="443" alt="Schermata 2020-10-29 alle 09 58 56" src="https://user-images.githubusercontent.com/4654358/97546982-7d883280-19cd-11eb-927a-78049d026c54.png">

Do you think is there a way to improve this behavior?

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
