### ISSUE TITLE
Project path with spaces breaks extension

### ISSUE THREAD

**Issue by ahcurrier** [apexskier/nova-eslint#280]
If my project path has spaces, this extension does nothing.

For example, my Nova project dir is named "Front End".

Doesn't work:
> $(npm bin)/eslint
/Users/username/Sites/Front: No such file or directory

Works:
> "$(npm bin)/eslint"

**Comment by ahcurrier** [comment]
Though perhaps I'm missing something?
I've installed the extension
  npm install --save-dev eslint eslint-plugin-compat
  Added browserslist to package.json
  npm init @eslint/config




+ When I run eslint from command line (quoted, see above), issues are found.
+ In the sidebar, says 'No issues found'.

**Comment by kopischke** [comment]
That’s #277 hitting you with its full power (spaces are encoded in URIs, this extension uses document URIs internally, and #276 removed the decoding step necessary to convert them back to file paths). Update Nova to version 9.1 and this extension to version 1.7.2 to get rid of the issue.

**Comment by kopischke** [comment]
Ugh, no, sorry, looks like 1.7.2 is still broken after #278 (see #279, #282). You will have to wait for #283 to be merged.
