### ISSUE TITLE
fix on save  gives error

### ISSUE THREAD

**Issue by JimFrostig** [apexskier/nova-eslint#294]
1. Set an Config file and set auto fix auf enable
2. Open a *.js File 
3. Save file, error comes up

Settings
<img width="1912" alt="Bildschirmfoto 2022-04-07 um 21 52 39" src="https://user-images.githubusercontent.com/6785519/162286233-95372d5c-a009-486a-ae94-65c403c67271.png">

Error
<img width="1912" alt="Bildschirmfoto 2022-04-07 um 21 51 45" src="https://user-images.githubusercontent.com/6785519/162286253-a515f0b8-0d07-4305-a4de-857e6a7199f4.png">

**Environment**

- Nova version: 9.1 rev 383286
- Extension version: 1.7.2
- ESLint version: 8.12.0
- macOS version: 12.3.1
- NodeJS information:
  - node version: v17.7.2 
  - npm version: 8.5.2
  - installation method: asdf nodejs plugin

Hi!
the problem with the plugin is i cant use the fix on save option. Everytime i run in an error (screenshot above). Is the problem by me or the plugin ?

Greetings ! 
Jim

**Comment by benjamineskola** [comment]
I think I'm having the same issue. Specifically, what seems to be occurring is that the path being passed to eslint for processing is missing the home directory prefix — so when I save `/Users/ben/Code/projectName/someJavascriptFile.js` I can see in the console that the arguments being passed are `/Code/nova-standardjs.novaextension/Scripts/main.js --fix --format=json`.

It looks like what's going wrong is the [cleanPath](https://github.com/apexskier/nova-eslint/blob/1fd54463b69118e6a2146d874cdbd87bfaa46615/src/process.ts#L223) variable, which I think is having too much of a prefix stripped. Changing the `slice(5)` to `slice(3)` works perfectly fine. I presume that in some other cases the path URI is being prefixed with `/Volumes/Macintosh HD` but on my machine it has no such prefix.

This may also affect the other occurrence of `cleanPath` on [L265](https://github.com/apexskier/nova-eslint/blob/1fd54463b69118e6a2146d874cdbd87bfaa46615/src/process.ts#L265) but I haven't tested that.

**Comment by benjamineskola** [comment]
This would be fixed by #283

**Comment by apexskier** [comment]
Resolved by https://github.com/apexskier/nova-eslint/pull/283

**Comment by apexskier** [comment]
Included in release [v1.7.3](https://github.com/apexskier/nova-eslint/releases/tag/v1.7.3)
