### ISSUE TITLE
"Error: failed to npm bin" on launch

### ISSUE THREAD

**Issue by eablokker** [apexskier/nova-eslint#321]
Often getting error dialog on launch saying "Error: failed to npm bin"

Error is intermittent. If I quit and relaunch it is gone. Usually happens on first launch.

Error dialog appears in every workspace I have open, so have to dismiss it multiple times.

I suggest using NotificationCenter to show error notification so that user doesn't have to dismiss multiple dialogs in order to use app.

**To reproduce**

1. Open Nova after rebooting system, with plugin activated. Doesn't happen every time.

**Expected behavior**

ESlint should not error, or at least show less intrusive error message.

**Environment**

- Nova version: 9.4
- Extension version: 1.7.3
- ESLint version: 8.15.0
- macOS version: 11.6.8
- NodeJS information:
  - node version: 12.22.8
  - npm version: 8.10.0
  - installation method: nvm

**Extension console output**

Will try to get next time it happens

**Comment by eablokker** [comment]
**Extension console output**

```
ESLint[15:31:14.279000] activating...

ESLint[15:31:27.503000] npm bin: env: npm: No such file or directory

ESLint[15:31:27.509000] Failed to activate

ESLint[15:31:27.510000] Error: failed to npm bin

ESLint[15:31:27.511000] activated

```

**Comment by yphoenix** [comment]
npm 9.x removed the bin command

**Comment by frenicohansen** [comment]
as an alternative $(npm root)/.bin/eslint can be used to get the binary location

**Comment by equinusocio** [comment]
I get the same issue just after installing, even before configuring it.

![CleanShot 2022-12-16 at 14 18 55](https://user-images.githubusercontent.com/10454741/208107054-5cabd035-946f-436a-a968-15a2c3f036d3.png)

Console doesn't tell much more:
![CleanShot 2022-12-16 at 14 21 16](https://user-images.githubusercontent.com/10454741/208107488-0a093d59-eb1f-4237-924d-28841423d5ef.png)



> as an alternative $(npm root)/.bin/eslint can be used to get the binary location

Can you explain this? Putting `$(npm root)/.bin/eslint` in the eslint executable field doesn't fix it. 

![CleanShot 2022-12-16 at 12 04 20](https://user-images.githubusercontent.com/10454741/208084809-7840f26d-1aee-4a04-af0a-f4ac274ffdb8.png)

**Comment by frenicohansen** [comment]
> I get the same issue just after installing, even before configuring it.
> 
> ![CleanShot 2022-12-16 at 14 18 55](https://user-images.githubusercontent.com/10454741/208107054-5cabd035-946f-436a-a968-15a2c3f036d3.png)
> 
> Console doesn't tell much more: ![CleanShot 2022-12-16 at 14 21 16](https://user-images.githubusercontent.com/10454741/208107488-0a093d59-eb1f-4237-924d-28841423d5ef.png)
> 
> > as an alternative $(npm root)/.bin/eslint can be used to get the binary location
> 
> Can you explain this? Putting `$(npm root)/.bin/eslint` in the eslint executable field doesn't fix it.
> 
> ![CleanShot 2022-12-16 at 12 04 20](https://user-images.githubusercontent.com/10454741/208084809-7840f26d-1aee-4a04-af0a-f4ac274ffdb8.png)

What I did was, to edit the code of the installed plugin. I forgot where the plugin's code is stored, but if I am not mistaken, there was an option from Nova to go to the plugin's folder. And then I change the code, which is responsible to find the eslint folder. https://github.com/apexskier/nova-eslint/blob/e21e008b3f854204161c09114c43000956ee7c35/src/getEslintPath.ts

I left Nova for VS Code, because there was plugins I needed, which only available for VS Code.

**Comment by zemlanin** [comment]
@equinusocio Right click on the extension in Extension Library, "Show in Finder", open `Scripts/main.dist.js` there, and Find-and-Replace `"bin"` to `"root"` (there should be a single `"bin"` in the whole file)

<img width="906" alt="Screenshot 2023-01-08 at 20 30 15" src="https://user-images.githubusercontent.com/711514/211215184-a308ae4b-72f2-421c-9a24-d17323f377a8.png">

**Comment by mrbbp** [comment]
this find-replace does not resolve the pb.
i got an error failed to find `usr/root/env`
there is more than ONE 'bin' in the main.dist.js …

`To verify you've set up correctly, run $(npm bin)/eslint ./path/to/file.js on a file and make sure the output is correct (no output if you don't expect issues, expected issues if you do).`
tested and output expected is done.

what's wrong?

have you a solution?
Nova without a linter, is useless

**Comment by equinusocio** [comment]
There is a pending PR but seems it will take bit longer...
https://github.com/apexskier/nova-eslint/pull/359

Hope Panic will make a built-in eslint extesion.

**Comment by mrbbp** [comment]
> There is a pending PR but seems it will take bit longer... #359
> 
> Hope Panic will make a built-in eslint extesion.

Thanks, I will be a good boy and patient :)

**Comment by mrbbp** [comment]
2 weeks passed and nothing happened.
Can we, should we hope for an update from Nova to use a linter or is it the extension that is the problem?
I'm a little lost on who does what!
Working without linter weighs on me.
regards

**Comment by equinusocio** [comment]
The pr has been merged days ago. Waiting the release from the maintainer.

**Comment by mrbbp** [comment]
the maintainer is dead, it's a sad day...

**Comment by apexskier** [comment]
Let's try to keep this constructive.

**Comment by equinusocio** [comment]
I find "constructive" letting people that the fix is done and waiting for release, instead of marking everything as off-topic. So people stop asking, even because none of the above wor around work.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
