### ISSUE TITLE
Preference to specify alternate ignore path

### ISSUE THREAD

**Issue by ashur** [apexskier/nova-eslint#322]
## Summary

An option to specify an alternate ignore file on a global and per-project basis — mirroring the functionality of the [`--ignore-path` CLI flag](https://eslint.org/docs/latest/user-guide/configuring/ignoring-code#using-an-alternate-file) — would be a really handy feature.

## Configuration

* **nova-eslint** — 1.7.3
* **Nova** — 9.4

## Severity

* Enhancement

## Notes

I definitely recognize that adding support for every possible `eslint` CLI option could become untenable very quickly 😅

If it would be easier to roll this behavior into a broader, more open-ended feature down the road that allowed extension users to define arbitrary options to be passed to the CLI, that would work just as well.

Thanks!

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
