### ISSUE TITLE
Cursor jumps to end of file after fixing

### ISSUE THREAD

**Issue by FilipAben** [apexskier/nova-eslint#369]
With fix on save, when saving a file, the cursor jumps to the end of file when eslint has finished fixing.

**To reproduce**

1. Enable fix on save
2. Save file
3. Wait a sec or so for linting to complete
4. Cursor jumps to the end of file

**Expected behavior**

Would expect cursor to remain (somewhat :) in place

**Screenshots**

**Environment**

- Nova version: 10.6
- Extension version: 1.7.4
- ESLint version: 12.2.1
- macOS version: 16.2
- NodeJS information:
  - node version: v19.6.0
  - npm version: 9.4.0
  - installation method: homebrew

**Extension console output**

No output

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
