### ISSUE TITLE
Error: failed to pm bin

### ISSUE THREAD

**Issue by oscarbrown4** [apexskier/nova-eslint#370]
I know this is a duplicate, but the comments are closed on the [other thread](https://github.com/apexskier/nova-eslint/issues/321).

Consistently every time I open a project, getting "Error: failed to npm bin" alert after updating to plugin version 1.7.4.  It looks like in the other thread that 1.7.4 was expected to fix this issue, but did not (and again, cannot comment).

<img width="529" alt="Screenshot 2023-02-09 at 9 19 43 AM" src="https://user-images.githubusercontent.com/3706162/217855447-173612af-ce49-4698-afe7-19caefd46496.png">
<img width="475" alt="Screenshot 2023-02-09 at 9 19 49 AM" src="https://user-images.githubusercontent.com/3706162/217855482-2015de13-bc67-4713-a221-5337ac06a4f8.png">

When i update the settings, per the other thread to make the Eslint Executable `$(npm root)/.bin/eslint` then it doesn't alert anymore, but the console says `No ESLint path` and ESLint just doesn't work.

<img width="421" alt="Screenshot 2023-02-09 at 9 25 17 AM" src="https://user-images.githubusercontent.com/3706162/217856477-f5740587-16bb-43b6-9424-ffb7ba955e35.png">

**Comment by leehord** [comment]
I've had some luck by setting the ESLint executable to the absolute path instead of `$(npm root)/.bin/eslint`

For example: `/Users/myusername/.nvm/versions/node/v18.15.0/lib/node_modules/eslint/bin/eslint.js`

This works for me but YMMV.

**Comment by rjfranco** [comment]
This error stems from npm bin no longer existing in npm 9+ I think this needs to be resolved somehow in code

**Comment by battis** [comment]
> I've had some luck by setting the ESLint executable to the absolute path instead of `$(npm root)/.bin/eslint`
> 
> For example: `/Users/myusername/.nvm/versions/node/v18.15.0/lib/node_modules/eslint/bin/eslint.js`
> 
> This works for me but YMMV.

My current fix is to change the plugin workspace path to the eslint executable to `node_modules/.bin/eslint` -- which is working, at least for now. (And I don't have to set the plugin per project… although this will, of course, break in a non-JS project where eslint is not already installed.)

**Comment by TwisterMc** [comment]
Installed the Eslint plugin today and it errored out on me too. 
> Error: failed to npm bin

**Comment by guillermo-avalos** [comment]
Having the same issue. Anyone found a fix yet?

**Comment by battis** [comment]
This is working consistently for me (but requires one to install eslint as a dev dependency: `npm i -D eslint`)
![image](https://github.com/apexskier/nova-eslint/assets/419619/e42137e5-5b9b-4c15-bbfe-8540e8b3c333)

**Comment by guillermo-avalos** [comment]
@battis Thank you! the error message went away with that setting. I guess it's working now.

**Comment by danieldickison** [comment]
It looks like #360 would fix this issue.

**Comment by eivindml** [comment]
Any movement on this?

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
