### ISSUE TITLE
incorrect error

### ISSUE THREAD

**Issue by davidbdyer** [apexskier/nova-eslint#388]
it's showing this error in a .mjs file 
`Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`
If the file had a .js extension that would be true but it has a .mjs so this error is wrong.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
