### ISSUE TITLE
Nova community Discord

### ISSUE THREAD

**Issue by apexskier** [apexskier/nova-eslint#4]
If you're interested in joining a new community discord to chat about Nova, extension development, or whatever, reach out to me and I'll send you an invite. (thanks to @henrikdahl for setting up it)

**Comment by zachgibson** [comment]
I'd like to join this discord. 😄

**Comment by apexskier** [comment]
@zachgibson send me an email I'll send you a link

**Comment by zachgibson** [comment]
zackgib@aol.com
