### ISSUE TITLE
uncaught exception for projects not using eslint

### ISSUE THREAD

**Issue by mrsdizzie** [apexskier/nova-eslint#406]
I notice in the extension console there are lots of errors like this:

```
ESLint[12:33:09.476000] 
Oops! Something went wrong! :(

ESLint: 8.42.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    npm init @eslint/config

ESLint looked for configuration files in /Users/isla/source/nova-perl-treesitter/perl-tree-sitter.novaextension and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint Discord server: https://eslint.org/chat

ESLint[12:33:09.476000] Extension encountered an uncaught exception:
/Users/isla/Library/Application Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js (Line 312, Column 28)
Error: failed to get eslint config for /Users/isla/source/nova-perl-treesitter/perl-tree-sitter.novaextension/CHANGELOG.md: 2
    @file:///Users/isla/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:312:28
    @[native code]

```
I don't use or intend to use eslint for this project, but see no way to stop it from checking and filling the console with errors like that on each save. I do have `fix on save` disabled in the project settings.

Can there be an option to not log and run eslint at all if the project has no existing eslint configuration file? or another way to totally disable it for a project?

Ideally the `ESLint couldn't find a configuration file.` would just be an indication to not use the extension rather than an error.

Thanks!

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
