### ISSUE TITLE
How to set options.rulePaths or --rulesdir

### ISSUE THREAD

**Issue by markholland** [apexskier/nova-eslint#68]
Our project has some rules we created and they are stored in a specific location.

I need a way to provide this path through either the options object or eslint arguments.

Can this be accomplished using this plugin?

**Comment by jbree** [comment]
You can go to Project > Project Settings…, find ESLint in the Extensions section on the side, then set the "Path to ESLint configuration".

If you'd prefer a global setting, look in Extensions > Extension Library…, find ESLint, then go to the Preferences tab to find a global version of the same setting.

**Comment by markholland** [comment]
I might be misunderstanding but I still want ESLint to use the project `.eslintrc.js` configuration file which is where the custom rules are enabled. I haven't seen a way to set additional rules directories in a configuration file, we have to pass it as a cli argument like so `eslint . --rulesdir=.eslint/rules`

**Comment by jbree** [comment]
Ah sorry, my misunderstanding. I assumed you were talking about configuration files 🤦🏻‍♂️

**Comment by apexskier** [comment]
Nova 4 has a new feature I've been hoping for that might help with this. I can now add preferences that are arrays of paths. I'm thinking about adding a preference for "Additional eslint arguments" that you can use to set things like this.

**Comment by apexskier** [comment]
~Alternatively,~ this could be supported in the same way a custom config file is supported - https://github.com/apexskier/nova-eslint/blob/6a2955df3dff623640101b612e883dbaec0203ca/ESLint.novaextension/extension.json#L60-L64, which aligns with how a custom binary is supported. ~A downside to that is that it doesn't support multiple values.~

~The only downside to using a string array is that you don't get the nice directory picker UI~

**Comment by apexskier** [comment]
https://github.com/apexskier/nova-eslint/pull/75 adds a config option for adding custom rules dirs. It appears there's a Nova bug preventing the preference from appearing globally when I restrict it to folders, but the workspace preference seems to work file. I'd appreciate someone trying it out locally before I merge and publish, since I don't usually use custom rules directories.
