### ISSUE TITLE
ESLint trying to verify files that are not JS

### ISSUE THREAD

**Issue by soapdog** [apexskier/nova-eslint#81]
I have an out-of-the-box installation of nova and ESLint without any special configuration. I'm editing shell scripts and ESLint is trying to lint them.

**To reproduce**

1. Create a shell script.
2. Edit the shell script.
3. Watch linter errors popup.

**Expected behavior**

ESLint should ignore shell scripts (in my case, the extension is .sh)

**Screenshots**

![image](https://user-images.githubusercontent.com/23247/106359390-7cd3a500-630a-11eb-9d70-2d3f28f57bba.png)

**Environment**

- Nova version: 4.3
- Extension version: 1.7.0
- ESLint version: 7.11
- macOS version: 11.1
- NodeJS information:
  - node version: 15.3
  - npm version: 7.0.14
  - installation method: nvm

**Extension console output**

Turn on extension development in Nova in Preferences > General > Extension Development. Then open the extension console with Extensions > Show Extension Console and copy anything coming from the Source "ESLint".
Copying text is preferred over screenshots, for accessibility and searching.

**Additional context**

**Comment by apexskier** [comment]
I think I know what's happening here.

The [extension explicitly shouldn't apply to this file type](https://github.com/apexskier/nova-eslint/blob/55c86cdd6550afb17db2c72750820265ca436c90/src/main.ts#L51-L63), but if you have a project that defaults to a supported file type, create a new file (of that type), then save it as a shell script, [this line](https://github.com/apexskier/nova-eslint/blob/55c86cdd6550afb17db2c72750820265ca436c90/src/main.ts#L99) will lint it always.

<img width="452" alt="ESLint Extension – test sh - Nova - 2021-01-31 at 11 00 25" src="https://user-images.githubusercontent.com/329222/106380583-87964480-63b3-11eb-9ad8-1860b3691be0.png">

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
